name: Create public release

on:
  workflow_run:
    workflows: [ Create Installer ]
    types: [ completed ]
    branches: [ feature/release_flow ]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: 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
        with:
          repo: package_release_test
          owner: ShalamovK
          draft: false
          prerelease: false
          release_name: v1.2.3
          tag_name: v1.2.3
          body: this is a test release